DernekOtomasyon.MVC/Controllers/NewsController.cs
using DernekOtomasyon.DATA.Entity;
using DernekOtomasyon.MVC.Controllers.Base;
using DernekOtomasyon.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DernekOtomasyon.MVC.Controllers
{
    public class NewsController : BaseController
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddCategory()
        {
            return View();
        }
        public ActionResult CategoryList()
        {
            List<Category> adminList = CategoryRepo.GetList().ToList();
            return View(adminList);
        }
        public ActionResult DeleteCategory(int ID)
        {
            Category a = CategoryRepo.FirstOrDefault(t => t.ID == ID);
            CategoryRepo.Delete(a.ID);
            _uow.SaveChanges();

            return RedirectToAction("CategoryList");

        }
        public ActionResult InsertCategory()
        {
            Category a = new Category();
            a.CategoryName = Request["category"];
            CategoryRepo.Insert(a);
            _uow.SaveChanges();
            return RedirectToAction("CategoryList");
        }

        public ActionResult AddNews()
        {
            NewsModel nm = new NewsModel();
            nm.CategoryList = CategoryRepo.GetList().ToList();

            return View(nm);
        }

        [ValidateInput(false)]
        public ActionResult InsertNews(HttpPostedFileBase file, string content)
        {
            var categoryid = Convert.ToInt32(Request["category"]);
            var memberId = Convert.ToInt32(Session["MemberID"]);

            News e = new News();
            e.Title = Request["title"];
            e.Spot = Request["spot"];
            e.CategoryID = categoryid;
            e.MemberID = memberId;
            e.Statu = 0;
            e.Content = content;
            e.Source = Request["source"];
            NewsRepo.Insert(e);
            _uow.SaveChanges();
            return RedirectToAction("NewsList");
        }

        public ActionResult NewsList()
        {
            List<News> EventList = NewsRepo.GetList().ToList();

            return View(EventList);
        }


        public ActionResult DeleteNews(int ID)
        {
            NewsRepo.Delete(ID);
            _uow.SaveChanges();
            return RedirectToAction("NewsList");
        }

        public ActionResult Onayla(int ID)
        {
            News news = NewsRepo.FirstOrDefault(t => t.ID == ID);
            news.Statu = 1;
            _uow.SaveChanges();
            return RedirectToAction("NewsList");
        }

        public ActionResult Report()
        {
            NewsModel nm = new NewsModel();
            nm.TotalCount = NewsRepo.GetList().Count();
            return View();
        }
    }
}

DernekOtomasyon.MVC/Views/News/AddCategory.cshtml
@{
    ViewBag.Title = "Kategori Oluştur";
}


<div class="row">
    <div class="col-lg-12 animatedParent animateOnce z-index-50">
        <div class="panel panel-default animated fadeInUp">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">Kategori Oluştur</h3>
                <ul class="panel-tool-options">
                    <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                    <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <form action="@Url.Action("InsertCategory","News")" method="post">
                    <div class="form-group">
                        <label for="emailaddress">Kullanıcı Adı</label>
                        <input type="text" class="form-control" name="category" placeholder="KAtegori adı..." />
                    </div>




                    <button type="submit" class="btn btn-primary">Gönder</button>

                </form>
            </div>
        </div>
    </div>

</div>

@section footerjs{


    <script src="@Url.Content("/js/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("/js/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

DernekOtomasyon.MVC/Views/News/AddNews.cshtml
@model DernekOtomasyon.MVC.Models.NewsModel
@{
    ViewBag.Title = "Kampanya Ekleme";
}

<div class="row">


    <div class="col-lg-12 animatedParent animateOnce z-index-46">
        <div class="panel panel-default animated fadeInUp go">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">Etkinlik Oluştur</h3>
                <ul class="panel-tool-options">
                    <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                    <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                </ul>
            </div>
            <div class="panel-body">


                <form id="validate-form" class="block-content form" action="@Url.Action("InsertNews","News")" method="post" enctype="multipart/form-data">




                    <label for="emailaddress">Kategori </label>
                    <div class="form-group alignflex">
                        <select name="category">
                            @foreach (var item in Model.CategoryList)
                            {
                                <option value="@item.ID">@item.CategoryName</option>
                            }
                        </select>



                    </div>



                    <label for="emailaddress">Haber Başlık</label>
                    <div class="form-group alignflex">

                        <input type="text" name="title" class="form-control required" placeholder="" value="" />

                    </div>


                    <label for="emailaddress">Spot</label>
                    <div class="form-group alignflex">

                        <input type="text" name="spot" class="form-control required" placeholder="" value="" />

                    </div>


                    <label for="emailaddress">İçerik</label>
                    <div class="form-group alignflex">

                        <textarea type="text" name="content" class="form-control required" placeholder="" value=""></textarea>

                    </div>


                    <label for="emailaddress">Kaynak</label>
                    <div class="form-group alignflex">

                        <input type="text" name="source" class="form-control required" placeholder="" value="" />

                    </div>
                    <button type="submit" class="btn btn-primary">Gönder</button>

                </form>

            </div>
        </div>
    </div>




</div>
<style>

    #FinishAt {
        background-image: url('/content/zebradatetimepicker/dist/css/bootstrap/icons.png');
        background-position: 98% -6%;
        background-repeat: no-repeat;
        cursor: pointer;
        border: 1px solid #a9a9a9;
    }
</style>

@section footerjs{
    <script src="@Url.Content(ViewBag.Path + "/ckeditor/ckeditor.js")"></script>

    <script src="@Url.Content(@ViewBag.Path + "/js/jquery.validate.min.js")" type="text/javascript"></script>

    <script type="text/javascript">



        $(document).ready(function () {




            $('#StartAt').Zebra_DatePicker({
                direction: true,
                pair: $('#FinishAt')
            });

            $('#FinishAt').Zebra_DatePicker({
                direction: 1,
                show_icon: false
            });



            /*
            * Form Validation
            */

            $('.categorypop').popover();






            //$("#validate-form").validate();

            $('#validate-form').validate({
                onfocusout: false,
                invalidHandler: function (form, validator) {
                    var errors = validator.numberOfInvalids();
                    if (errors) {
                        validator.errorList[0].element.focus();
                    }
                },
                rules: {


                },
                errorPlacement: function (error, element) {
                    if (element.is(":radio")) {
                        error.appendTo(element.parents('.container'));
                    }
                    else { // This is the default behavior
                        error.insertAfter(element);
                    }
                },
                messages: {



                }
            });

        });


    </script>
}

DernekOtomasyon.MVC/Views/News/CategoryList.cshtml
@model IEnumerable<DernekOtomasyon.DATA.Entity.Category>
@{
                /**/
}

<div class="row">
    <div class="col-lg-12 animatedParent animateOnce z-index-50">
        <div class="panel panel-default animated fadeInUp">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">Kategoriler </h3>
                <ul class="panel-tool-options">
                    <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                    <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table data-page-length='50' class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Kategori Adı</th>
                                <th>DETAY</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr id="Coupon_1" class="gradeX">




                                    <td>@item.CategoryName</td>
                                    <td>
                                        <a class="btn btn-success userbutton categorypop" data-placement="top" data-trigger="hover" data-content="PASİF YAP" href="#"><i class="fa fa-eye"></i></a>
                                        <a class="btn btn-red userbutton categorypop" data-placement="top" data-trigger="hover" data-content="SİL" href="@Url.Action("DeleteCategory","News", new { ID = item.ID } )"><i class="fa fa-times"></i></a>

                                    </td>




                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




@section footerjs{


    <script src="@ViewBag.Path/js/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/jszip.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/pdfmake.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/vfs_fonts.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                order: [0, "desc"],
                dom: '<"html5buttons" B>lTfgitp',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: 'Kopyala',
                        exportOptions: {
                            columns: [0, ':visible']
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'colvis',
                        text: 'Sütun Göster/Gizle'
                    },
                ]
            });
        });
    </script>

    <link href="~/css/PagerList.css" rel="stylesheet" />

    <link href="@ViewBag.Path/css/mouldifi-forms.css" rel="stylesheet">
    <link href="@ViewBag.Path/css/plugins/datatables/jquery.dataTables.css" rel="stylesheet">
    <link href="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/css/buttons.dataTables.css" rel="stylesheet">
}

DernekOtomasyon.MVC/Views/News/NewsList.cshtml
@model IEnumerable<DernekOtomasyon.DATA.Entity.News>
@{
}

@if (Session["Message"] != null)
{

    <span class="btn btn-info">@Session["Message"].ToString()</span>
}
<div class="row">
    <div class="col-lg-12 animatedParent animateOnce z-index-50">
        <div class="panel panel-default animated fadeInUp">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">Etkinlikler</h3>
                <ul class="panel-tool-options">
                    <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                    <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table data-page-length='50' class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Haber Başlık</th>
                                <th>Kategori</th>
                                <th>Yayın Tarihi</th>
                                <th>Ekleyen Editör</th>
                                <th>DETAY</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {


                                <tr id="Coupon_1" class="gradeX">

                                    <td>@item.ID</td>
                                    <td>@item.Title</td>
                                    <td>@item.Category.CategoryName</td>
                                    <td>@item.InsertedDate</td>
                                    <td>@item.Member.Username</td>
                                    <td>
                                        @if (Session["Admin"] != null)
                                        {

                                            <a href="@Url.Action("Onayla","News", new { ID = item.ID })" class="btn btn-success userbutton categorypop" data-placement="top" data-trigger="hover" data-content="KATIL">ONAYLA</a>
                                        }
                                        <a href="@Url.Action("DeleteNews","News", new { ID = item.ID })" class="btn btn-red userbutton categorypop" data-placement="top" data-trigger="hover" data-content="SİL" onclick="DeleteCoupon('0')"><i class="fa fa-times"></i></a>

                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




@section footerjs{


    <script src="@ViewBag.Path/js/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/jszip.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/pdfmake.min.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/vfs_fonts.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js"></script>
    <script src="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js"></script>
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                order: [0, "desc"],
                dom: '<"html5buttons" B>lTfgitp',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: 'Kopyala',
                        exportOptions: {
                            columns: [0, ':visible']
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'colvis',
                        text: 'Sütun Göster/Gizle'
                    },
                ]
            });
        });
    </script>

    <link href="~/css/PagerList.css" rel="stylesheet" />

    <link href="@ViewBag.Path/css/mouldifi-forms.css" rel="stylesheet">
    <link href="@ViewBag.Path/css/plugins/datatables/jquery.dataTables.css" rel="stylesheet">
    <link href="@ViewBag.Path/js/plugins/datatables/extensions/Buttons/css/buttons.dataTables.css" rel="stylesheet">
}